### PR TITLE
Bionic upgrade

### PR DESCRIPTION
**Pull request by LeePorte**
## Changes proposed in this pull request:

Here's a PR based on our recent work on migrating over to Bionic using our fork of this repo. We discovered that automake-1.15 was too old to run on bionic so it made sense to upgrade to automake-1.16.3 and bounce autoconf and ionotify-tools at the same time. 

## security considerations

Migrates the boshrelease over to a supported stemcell

### CODE REVIEW

**Comment by ccostino** [comment]
Thank you, @LeePorte!  We appreciate this and our team will be taking a look to review as soon as we can.  We'll let you know if we have any questions. :-)

**Comment by ccostino** [comment]
@LeePorte we're starting to work through testing and incorporating this PR into our pipeline(s).  It'll take us a bit of time to work through this, but our initial tests today show that this should be 👍 for us. :-)

Thank you again for submitting this, we greatly appreciate it!

**Review by ChrisMcGowan — APPROVED** [review]
moved PR to commit to bionic branch so we can maintain 2 versions of the release as we migrate stemcells

**Comment by LeePorte** [comment]
Glad you found it a useful PR. Makes sense to share the load

**Pull request merged**
